### ISSUE TITLE
A dont-touch-the-drive boot setup?

### ISSUE THREAD

**Issue by konradybcio** [AsahiLinux/docs#10]
Would it be possible to boot m1n1, or any other payload for that matter without altering whatever is currently on the internal ssd, including omitting the re-partitioning?
I am not yet very familiar with the limitations of kmutil and friends, but if they allowed for marking an image on an external volume as bootable, I don't see why not?

Obviously, once we jump to Linux, it's not a problem to run from an external storage medium, but I don't think there is any info about getting m1n1 on anything other than the internal drive on the wiki currently..

**Comment by marcan** [comment]
The machines do not support booting from external storage, so it is impossible to boot from external storage without touching the internal SSD. This applies to macOS too. Booting macOS installs from external storage is accomplished behind the scenes by copying the entire boot structure (kernel, iBoot2, firmwares, etc.) to the internal SSD. The bootloader does not support USB devices at all.

**Comment by konradybcio** [comment]
Understood, thanks!

**Comment by marcan** [comment]
Just to add a bit more info: it is possible to avoid an outright top-level re-partition by installing the stub into the existing macOS container, since one APFS container can host multiple OSes. However, I currently do not support this because it makes cleanup a bit more involved; deleting the new OS ends up requiring nuking multiple volumes as well as files under certain directories in existing volumes, which is harder to get right. At this point it feels safer to just ask people to re-partition and then you can just delete the entire container/partition to start over.

I'd be up for supporting this in the future as a feature in the installer; the two use cases where this would be useful would be external boot as you say (which at this point would have to use an external EFI partition; U-Boot can do that but we'd probably have to offer an option to configure such an install that's distinct from an internal-boot mode which would know what EFI partition to look for), and also in the future it might be possible to use APFS as a root filesystem for Linux and have true space-sharing coexistence with macOS. But that's a bit in the future.

I'm not sure if we can outright provision an "external" OS the same way macOS does it, i.e. in a way that Apple's tooling will copy the necessary boot files to internal storage (which happens in the iBootSystemContainer partition, no need to create new volumes anywhere, although there are space restrictions). We certainly can't do that in a way that would boot on any machine, since we need kmutil to create a local boot policy. But it *might* be possible to do it for a single machine? I don't know; I haven't tried. It feels a bit academic to support this use case but it might make sense for some people?
