### ISSUE TITLE
Is suspend to disk/hibernate working?

### ISSUE THREAD

**Issue by gronka** [AsahiLinux/docs#39]
This part of the docs might be saying no, but I don't know if PSCI is required for suspend to disk.

https://github.com/AsahiLinux/docs/wiki/Feature-Support#power

**Comment by marcan** [comment]
Suspend to disk probably won't be supported for a long time, as it's a much more difficult problem than suspend to RAM due to having to restore firmware state.

Closing since this is a known issue and unlikely to move forward any time soon, especially as we introduce support for more complex hardware.
