### ISSUE TITLE
wired headphones not working.

### ISSUE THREAD

**Issue by monomycelium** [AsahiLinux/docs#54]
Hello. I know that the speakers do not work. But headphones connected through the 3.5 mm jack should work, right? Well, mine is not working. I've tried following the other issue about this on the `linux` repository, but it did not work for me. What should I do?

**Comment by jannau** [comment]
Yes, headphone audio should work and does here. Please provide more information about your system. To start, please attach the output of `asahi-diagnose` to this issue.

**Comment by monomycelium** [comment]
Here are the diagnostics: [asahi-diagnose-20230123-114137.txt](https://github.com/AsahiLinux/docs/files/10476569/asahi-diagnose-20230123-114137.txt).

I have tried testing if the headphones work if I install `asahi-desktop-meta`, but it still fails to work.

**Comment by marcan** [comment]
How are you testing? What app/sound server are you using?

Note that audio is only expected to work "out of the box" if you use PipeWire (because PulseAudio is broken and nothing else implements modern audio configuration properly, plus future speaker support will rely on PipeWire DSP profiles). If you are trying to use raw ALSA or some other sound server, you will have to manually apply/manage the ALSA controls to make it work, and you will have to DIY the entire speaker audio processing pipeline once we enable that for end users.

**Comment by monomycelium** [comment]
> How are you testing? What app/sound server are you using?

By testing, I meant just trying to connect my headphones through the 3.5 mm jack and seeing if it can play audio. I just went to System Settings, and fiddled with stuff in the Audio section to no avail. I have tried both sound servers (even restarting to be sure) but it did not work.

**Comment by maxchristman** [comment]
I am having a similar issue, albeit using Gentoo Linux through chadmed's Asahi support repo: https://github.com/chadmed/asahi-gentoosupport

**Comment by monomycelium** [comment]
@maxchristman, I actually got sound output to work from the headphone jack in Gentoo Linux on my M1 MacBook Air. First, I got Plasma working with the `pulseaudio`. Then, I emerged `alsa-ucm-conf-asahi` as well as `media-sound/alsa-utils`. I ran `alsamixer` to see if things were right. Then, I added `alsasound` to the `boot` runlevel and restarted. Now, my wired headphones work flawlessly on my M1 Mac (in Gentoo, at least).

**Comment by hamza72x** [comment]
@monomycelium hey, can you elaborate more? With necessary steps? I am using Debian Asahi, and sound is not working with Headphone/Speaker both. I can't figure out your comment that you said. Please elaborate with necessary steps. Thank you.

**Comment by monomycelium** [comment]
@hamza72x, basically, I installed some packages, `alsa-ucm-conf-asahi` and `alsa-utils`, then enabled the `alsasound` service. The names of the packages or service may differ, though.

**Comment by lakshaygarg755** [comment]
In asahi linux just run two commands
sudo pacman -Sy alsa-ucm-conf-asahi
Then
sudo pacman -Sy alsa-utils
And now you can use wired headphones

**Comment by hamza72x** [comment]
@lakshaygarg755 still not working in a fresh install. The settings shows the "headphone", but it is not working.

Device: 16" Macbook Pro (M1 Pro, 16/512)

**Comment by lakshaygarg755** [comment]
@hamza72x 
Actually i uninstalled asahi and installed Ubuntu. I would also recommend Ubuntu to you.
In Ubuntu sound is working in both wired and wireless headphones.
Here's the tutorial
https://youtu.be/aXh_d1OixRI?si=wyUG-up5bSeot3po

**Comment by hamza72x** [comment]
@lakshaygarg755 installed the Ubuntu version of Asahi (audio worked there), but currently "Chroimum/Chrome" engine is not supported without `--no-sandbox`

So again backed to main Asahi, due to my workflow.

**Comment by jannau** [comment]
Please create separate new issues if the wired headphones on fresh KDE AsahiLinux (alarm) or Fedora installs are not working. There are currently reports that they do not work on Fedora which I can not reproduce.

Please note that the headphones will only show up while plugged in. Do not modify the audio setting (alsamixer/pipewire) beforehand. If you did switch back to the profile `n/a`. Do not be alarmed by `n/a`. It is caused by a missing field in a config file and will be fixed soon.
