### ISSUE TITLE
Failed to find NVMe on Gentoo install guide

### ISSUE THREAD

**Issue by maxchristman** [AsahiLinux/docs#55]
After installing Asahi minimal, switching to `asahi-dev`, and rebooting, the system cannot find the NVMe drive and refuses to boot. I am confused why we should switch to `asahi-dev`. I also [asked marcan this on Reddit](https://www.reddit.com/r/AsahiLinux/comments/10l8s2d/minimal_install_failure_with_asahidev/) and he says that any guide which suggests to switch to `asahi-dev` is wrong.

Here's the output image:
![IMG_0694](https://user-images.githubusercontent.com/54341372/214952392-572eed69-2e0b-4126-bc44-de8b8031a6e3.jpeg)

**Comment by chadmed** [comment]
The switch to `asahi-dev` was from a long time ago when the stock kernel config was missing a couple of options.
This has since been rectified. I do try to test releases before pushing them but I must've missed something this time. Reinstall Asahi and try again now that this is fixed.

In the future, please file any issues at `asahi-gentoosupport`.

**Comment by maxchristman** [comment]
Thank you for letting me know. I appreciate your work maintaining Gentoo support for Asahi. I was able to reinstall without switching without issue.
