### ISSUE TITLE
Camera artifacts on Fedora Remix |M2 Macbook Pro 14 Inch | Hyprland wm

### ISSUE THREAD

**Issue by burakssen** [AsahiLinux/docs#86]
![2023-10-28-220302_hyprshot](https://github.com/AsahiLinux/docs/assets/43742977/905e55db-2307-49cb-bceb-997dbba34083)
![2023-10-28-220826_hyprshot](https://github.com/AsahiLinux/docs/assets/43742977/d992759a-77ae-4677-bc61-dc61d603f0cb)

There are visual artifacts when I try to use cheese application on fedora Hyprland. I have checked and its same with the Gnome.

**Comment by jannau** [comment]
This is a bug Cheese. It doesn't handle capture surfaces with line padding (each line has to be ignored data at the end so that the next line starts at a multiple of 64). Try a different format, the ones which have a larger width than height should be all ok (width is a multiple of 64).
Was this capture format selected by default?

**Comment by burakssen** [comment]
Ok thank you for pointing out. I've just checked with different resolutions and it works perfectly.
Yes it's selected by default (1440x1920).
